### ISSUE TITLE
slower with threads on

### ISSUE THREAD

**Issue by mattaylor** [dom96/httpbeast#19] opened 2018-12-11 21:15 UTC
Running the server with threads appears to introduce significant performance penalties..

With `--threads = on` (8 threads) : 
```bash
Running 10s test @ http://localhost:8000/text
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   282.46us   71.12us   1.45ms   79.08%
    Req/Sec    17.51k   764.96    18.69k    80.69%
  352091 requests in 10.10s, 46.34MB read
Requests/sec:  34859.58
Transfer/sec:      4.59MB
```
Without threads (1 thread): 
```
Running 10s test @ http://localhost:8000/text
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   200.23us   40.78us   0.97ms   85.91%
    Req/Sec    24.58k     0.92k   25.83k    82.67%
  494158 requests in 10.10s, 65.03MB read
Requests/sec:  48926.05
Transfer/sec:      6.44MB
```

**Comment by dom96** [comment] 2018-12-11 22:07
Compiled with -d:release?

**Comment by mattaylor** [comment] 2018-12-11 22:12
yep
see https://github.com/mattaylor/whip for source

**Comment by jamiesonbecker** [comment] 2019-04-18 20:12
Running simple Hello World demo with Jester:

```
# example.nim
import htmlgen
import jester

routes:
  get "/":
      resp h1("Hello world")
```

**Results on Intel i7-8700k**

*Threads on:*

```
$ nim --threads:on --opt:speed -d:release c -r example.nim
# (control-C, restart ./example)
# displays Starting 12 threads
$ wrk -c 10000 -d 5 http://localhost:5000/
Running 5s test @ http://localhost:5000/
  2 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    32.37ms   11.25ms 146.05ms   91.05%
    Req/Sec    80.79k     9.65k   93.68k    80.00%
  755726 requests in 5.01s, 110.99MB read
Requests/sec: 150701.68
Transfer/sec:     22.13MB
```

*Threads off:*

```
$ nim --opt:speed -d:release c -r example.nim
# (control-C, restart ./example)
# displays Starting 1 threads
$ wrk -c 10000 -d 5 http://localhost:5000/
Running 5s test @ http://localhost:5000/
  2 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   129.35ms   27.85ms   1.99s    89.05%
    Req/Sec    31.72k     6.99k   41.07k    69.15%
  297535 requests in 5.03s, 43.70MB read
  Socket errors: connect 0, read 0, write 0, timeout 41
Requests/sec:  59178.14
Transfer/sec:      8.69MB
```

Threads on seems to have a positive impact here.

**Comment by jamiesonbecker** [comment] 2019-04-18 20:18
For reference, running against a *static* `<h1>Hello world</h1>` `index.html` file on nginx on the same host:

```
Running 5s test @ http://localhost/
  2 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    32.21ms  152.42ms   1.72s    97.35%
    Req/Sec    82.06k    16.04k  113.37k    76.04%
  791354 requests in 5.06s, 294.33MB read
  Socket errors: connect 0, read 2404, write 0, timeout 526
Requests/sec: 156435.19
Transfer/sec:     58.18MB
```

**Comment by dom96** [comment] 2019-04-19 12:30
Yeah, I don't understand why it's slower for @mattaylor.

@jamiesonbecker your numbers are with Jester as well, right? you should try this https://github.com/dom96/httpbeast/blob/master/tests/benchmark.nim

**Comment by dom96** [comment] 2019-04-19 12:31
It's also strange that @mattaylor's whip framework apparently uses httpbeast and yet is somehow faster in this benchmark table? https://github.com/mattaylor/whip#its-fast

**Comment by jamiesonbecker** [comment] 2019-04-19 14:26
@dom96 good thought - I might go back and do them again (although they were really just for fun and not rigorous... I didn't prewarm or set my cpufreq governor or anything like that -- it was just really shocking to see `httpbeast` basically beat `nginx`, especially since the nginx run had the benefit of running last, as an afterthought; I should add in a lua/openresty 'helloworld' and see how that compares, though, since that would be more apples-to-apples to what jester was doing.)

In that table https://github.com/mattaylor/whip#its-fast , @mattaylor doesn't seem to be running threads on for `httpbeast`, since it says the `wrk` runs were with only 2 threads (although CPU not specified, but with threads off above `httpbeast` also said two threads for me). If threads on resulted in 3x performance boost as it did for me above, then it appears that httpbeast would be by far the fastest of the tested configurations.

My guess is that the original numbers above were just bad or old, and that the same config was used to generate that benchmark table.

I would be curious as to how those numbers were generated... perhaps there's a difference in kernel configuration, ie max open files / ulimit, etc (although that should have raised an error if exhausted), or maybe a clang/gcc change, or something related to how it was built.

**Comment by ajusa** [comment] 2021-12-03 06:05
Hm, I think I've been able to reproduce this on a Raspberry Pi, at least using Jester. Keep in mind that I'm running wrk on a different machine than the server, so the earlier point shouldn't affect me. 
Single threaded:
```
Running 5s test @ http://192.168.1.150:5000/
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    21.29ms    8.24ms 245.69ms   91.46%
    Req/Sec     2.36k   408.37     2.83k    82.00%
  23479 requests in 5.01s, 19.88MB read
Requests/sec:   4687.01
Transfer/sec:      3.97MB
```
Multithreaded:
```
Running 5s test @ http://192.168.1.150:5000/
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    25.70ms   13.01ms 249.56ms   83.98%
    Req/Sec     2.00k   581.67     2.83k    75.00%
  19938 requests in 5.01s, 16.88MB read
Requests/sec:   3979.85
Transfer/sec:      3.37MB
```
So it's almost 20% slower in this case, no clue why. At least with a Raspberry Pi it should be easier to reproduce for others?

**Comment by ajusa** [comment] 2021-12-03 06:10
And with the latest httpbeast on master, it's even worse?
Multithreaded:
```
Running 5s test @ http://192.168.1.150:5000/
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    52.68ms   37.17ms 360.36ms   94.94%
    Req/Sec     1.03k   230.99     1.62k    76.53%
  10099 requests in 5.01s, 8.55MB read
Requests/sec:   2015.80
Transfer/sec:      1.71MB
```
That's about half the speed? This is super weird, since I've benchmarked this exact code on my laptop and seen threads improve performance significantly, usually double the performance on my quad core machine.

**Comment by dom96** [comment] 2021-12-03 15:11
@ajusa hmmm, your numbers look suspicious for either single-threaded or multi-threaded. You sure your network isn't bottlenecking this and you just got lucky that the numbers were lower for the multi-threaded variant?

**Comment by ajusa** [comment] 2021-12-03 17:28
Yep, I think you may be right. After running this a couple more times, I'm seeing some pretty large variance. It is most likely due to heat, frequency boosting, or a network/IO bottleneck. Both tend to perform pretty closely. At this point, you may be able to close this issue unless someone else is able to reproduce this.

Having said that, I do think that there is room for improvement with threads. When I give it four more cores on my laptop, I only get 2x performance - this might be worth looking into. I've glanced over the code and don't see anything obvious though...

**Comment by dom96** [comment] 2021-12-03 17:52
> Having said that, I do think that there is room for improvement with threads. When I give it four more cores on my laptop, I only get 2x performance - this might be worth looking into. I've glanced over the code and don't see anything obvious though...

Definitely. But I would also be cautious of how this was tested, if you ran `wrk` on the same laptop then that might explain it.

Whereas in techempower the scalability of httpbeast seems to be in-line with that of the top-tier servers (for example compare httpbeast to ulib-json_fit in https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=json)

**Closed** 2021-12-03 17:54 UTC
